language: python
python:
  - "3.6"
install:
  - python setup.py install
  - pip install pytest

script:
  - pytest -s -v tests/default.py

notifications:
  webhooks:
    urls:
      - https://$WEBHOOK_USER:$WEBHOOK_PASSWORD@events.smetj.net/travis
